services:
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    env_file:
      - ./backend/.env
    environment:
      PORT: 8000
      HOST: 0.0.0.0
    expose:
      - "8000"
    networks: [appnet]
    restart: unless-stopped

  nginx:
    build:
      context: ./frontend       # usa o Dockerfile do front (o multi-stage que gera /dist e copia p/ nginx)
      dockerfile: dockerfile
      args:
        VITE_API_URL: "/api"
    ports:
      - "80:80"
    depends_on:
      - backend
    networks: [appnet]
    restart: unless-stopped

networks:
  appnet:
