# ========= deps (instala só produção) =========
FROM node:20-alpine AS deps
WORKDIR /app
COPY package*.json ./
# cache do npm ajuda muito em VPS
RUN --mount=type=cache,target=/root/.npm \
    npm ci --omit=dev --no-audit --no-fund

# ========= runner =========
FROM node:20-alpine
WORKDIR /app
ENV NODE_ENV=production
# copia node_modules prontos
COPY --from=deps /app/node_modules ./node_modules
# copia o código
COPY . .
EXPOSE 8000
CMD ["node", "src/index.js"]
